data =[
    "United States_Male_Basic_Smartphone",
    "Canada_Female_Premium_Tablet",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Female_Standard_Laptop",
    "Germany_Male_Basic_Smartphone",
    "France_Female_Premium_Smart TV",
    "Brazil_Male_Standard_Tablet",
    "Mexico_Female_Basic_Laptop",
    "Spain_Male_Standard_Smartphone",
    "Italy_Female_Premium_Smart TV",
    "United States_Female_Basic_Smartphone",
    "Canada_Male_Premium_Tablet",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Basic_Smartphone",
    "Germany_Female_Standard_Smart TV",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Italy_Male_Basic_Tablet",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Standard_Tablet",
    "Germany_Female_Basic_Laptop",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Premium_Laptop",
    "Italy_Male_Basic_Smartphone",
    "United States_Female_Premium_Smart TV",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Standard_Smartphone",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Italy_Male_Basic_Tablet",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Standard_Tablet",
    "Germany_Female_Basic_Laptop",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Premium_Laptop",
    "Italy_Male_Basic_Smartphone",
    "United States_Female_Premium_Smart TV",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Standard_Smartphone",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Italy_Male_Basic_Tablet",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Standard_Tablet",
    "Germany_Female_Basic_Laptop",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Premium_Laptop",
    "Italy_Male_Basic_Smartphone",
    "United States_Male_Basic_Smartphone",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Female_Premium_Smartphone",
    "Germany_Female_Basic_Laptop",
    "France_Female_Basic_Laptop",
    "Brazil_Female_Premium_Smartphone",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Standard_Laptop",
    "Italy_Male_Basic_Tablet",
    "United States_Male_Premium_Tablet",
    "Canada_Male_Standard_Laptop",
    "United Kingdom_Female_Basic_Smartphone",
    "Australia_Male_Standard_Smartphone",
    "Germany_Female_Premium_Laptop",
    "France_Female_Basic_Smartphone",
    "Brazil_Male_Premium_Smart TV",
    "Mexico_Male_Standard_Tablet",
    "Spain_Male_Basic_Smartphone",
    "Italy_Female_Standard_Smartphone",
    "United States_Male_Premium_Tablet",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Premium_Smartphone",
    "Germany_Male_Basic_Laptop",
    "France_Male_Premium_Laptop",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Female_Standard_Tablet",
    "Spain_Female_Standard_Tablet",
    "Italy_Male_Basic_Laptop",
    "United States_Female_Premium_Tablet",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Premium_Laptop",
    "Germany_Female_Basic_Laptop",
    "France_Female_Premium_Tablet",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Female_Standard_Tablet",
    "Italy_Female_Basic_Laptop",
    "United States_Male_Premium_Tablet",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Male_Premium_Smartphone",
    "Germany_Female_Basic_Laptop",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Standard_Smartphone",
    "Italy_Female_Basic_Smart TV",
    "United States_Male_Premium_Smart TV",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Premium_Laptop",
    "Germany_Male_Basic_Smartphone",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Standard_Smart TV",
    "Italy_Female_Basic_Tablet",
    "United States_Male_Premium_Laptop",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Tablet",
    "Germany_Female_Basic_Smart TV",
    "France_Female_Premium_Smart TV",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Standard_Smartphone",
    "Italy_Female_Basic_Smartphone",
    "United States_Male_Premium_Smartphone",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Premium_Smart TV",
    "Germany_Female_Basic_Laptop",
    "France_Male_Basic_Tablet",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Italy_Female_Basic_Laptop",
    "United States_Female_Basic_Laptop",
    "Canada_Female_Premium_Tablet",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Standard_Laptop",
    "Germany_Male_Basic_Tablet",
    "France_Male_Premium_Smartphone",
    "Brazil_Male_Standard_Laptop",
    "Mexico_Female_Basic_Smartphone",
    "Spain_Female_Standard_Smart TV",
    "Italy_Male_Premium_Smartphone",
    "United States_Male_Basic_Tablet",
    "Canada_Male_Premium_Laptop",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Basic_Tablet",
    "Germany_Male_Standard_Tablet",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Male_Standard_Tablet",
    "Spain_Male_Premium_Tablet",
    "Italy_Male_Basic_Laptop",
    "United States_Female_Premium_Tablet",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Standard_Tablet",
    "Germany_Female_Basic_Laptop",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Premium_Tablet",
    "Italy_Male_Basic_Laptop",
    "United States_Male_Premium_Smartphone",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Standard_Laptop",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Italy_Female_Basic_Tablet",
    "United States_Male_Premium_Laptop",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Standard_Laptop",
    "Germany_Female_Basic_Smartphone",
    "France_Female_Premium_Smart TV",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Premium_Tablet",
    "Italy_Female_Basic_Tablet",
    "United States_Female_Premium_Smart TV",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Standard_Smartphone",
    "Germany_Male_Basic_Smart TV",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Premium_Laptop",
    "Italy_Female_Basic_Laptop",
    "United States_Male_Premium_Tablet",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Female_Standard_Laptop",
    "Germany_Female_Basic_Smartphone",
    "France_Female_Premium_Smart TV",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Premium_Smartphone",
    "Italy_Male_Basic_Tablet",
    "United States_Male_Basic_Smartphone",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Premium_Smartphone",
    "Germany_Female_Basic_Smartphone",
    "France_Male_Basic_Smartphone",
    "Brazil_Female_Premium_Smartphone",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Male_Standard_Smartphone",
    "Italy_Male_Basic_Laptop",
    "United States_Male_Premium_Smartphone",
    "Canada_Male_Standard_Smartphone",
    "United Kingdom_Female_Basic_Smart TV",
    "Australia_Female_Standard_Laptop",
    "Germany_Male_Premium_Laptop",
    "France_Female_Basic_Smartphone",
    "Brazil_Female_Premium_Tablet",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Basic_Smart TV",
    "Italy_Male_Standard_Smartphone",
    "United States_Male_Premium_Laptop",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Premium_Smartphone",
    "Germany_Male_Basic_Smart TV",
    "France_Female_Premium_Smartphone",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Standard_Smartphone",
    "Italy_Male_Basic_Laptop",
    "United States_Male_Premium_Laptop",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Premium_Smart TV",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Tablet",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Male_Standard_Smartphone",
    "Italy_Female_Basic_Smartphone",
    "United States_Female_Premium_Smart TV",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Premium_Smartphone",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Female_Standard_Laptop",
    "Italy_Male_Basic_Smart TV",
    "United States_Male_Premium_Laptop",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Female_Premium_Tablet",
    "Germany_Female_Basic_Laptop",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Standard_Laptop",
    "Italy_Female_Basic_Laptop",
    "United States_Female_Premium_Smart TV",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Premium_Smartphone",
    "Germany_Female_Basic_Laptop",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Female_Standard_Smart TV",
    "Italy_Male_Basic_Smartphone",
    "United States_Female_Premium_Tablet",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Premium_Laptop",
    "Germany_Male_Basic_Laptop",
    "France_Female_Basic_Tablet",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Male_Standard_Tablet",
    "Spain_Male_Premium_Smartphone",
    "Italy_Male_Basic_Laptop",
    "United States_Female_Basic_Laptop",
    "Canada_Male_Premium_Tablet",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Standard_Smartphone",
    "Germany_Male_Basic_Smart TV",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Standard_Smart TV",
    "Mexico_Male_Basic_Smart TV",
    "Spain_Male_Standard_Smartphone",
    "Italy_Female_Premium_Smartphone",
    "United States_Female_Basic_Smartphone",
    "Canada_Male_Premium_Laptop",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Basic_Laptop",
    "Germany_Female_Standard_Smart TV",
    "France_Female_Premium_Laptop",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Premium_Smartphone",
    "Italy_Female_Basic_Laptop",
    "United States_Female_Premium_Smartphone",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Standard_Tablet",
    "Germany_Male_Basic_Tablet",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Tablet",
    "Spain_Female_Premium_Smart TV",
    "Italy_Female_Basic_Smart TV",
    "United States_Female_Premium_Tablet",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Standard_Smart TV",
    "Germany_Female_Basic_Tablet",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Premium_Laptop",
    "Italy_Female_Basic_Smartphone",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Female_Standard_Smartphone",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Tablet",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Male_Premium_Smartphone",
    "Italy_Female_Basic_Smartphone",
    "United States_Female_Premium_Smart TV",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Standard_Laptop",
    "Germany_Female_Basic_Tablet",
    "France_Male_Premium_Smart TV",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Premium_Smartphone",
    "Italy_Female_Basic_Tablet",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Standard_Smart TV",
    "Germany_Male_Basic_Laptop",
    "France_Male_Premium_Smart TV",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Premium_Smartphone",
    "Italy_Female_Basic_Smartphone",
    "United States_Male_Basic_Tablet",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Premium_Laptop",
    "Germany_Female_Basic_Laptop",
    "France_Female_Basic_Smartphone",
    "Brazil_Male_Premium_Laptop",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Standard_Smart TV",
    "Italy_Female_Basic_Smart TV",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Standard_Smart TV",
    "United Kingdom_Male_Basic_Smart TV",
    "Australia_Female_Standard_Smartphone",
    "Germany_Male_Premium_Smartphone",
    "France_Male_Basic_Tablet",
    "Brazil_Female_Premium_Tablet",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Basic_Smart TV",
    "Italy_Female_Standard_Laptop",
    "United States_Male_Premium_Laptop",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Premium_Tablet",
    "Germany_Female_Basic_Laptop",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Tablet",
    "Spain_Female_Standard_Smartphone",
    "Italy_Male_Basic_Laptop",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Premium_Smartphone",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Standard_Smartphone",
    "Italy_Male_Basic_Smart TV",
    "United States_Female_Premium_Tablet",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Premium_Laptop",
    "Germany_Female_Basic_Smartphone",
    "France_Male_Premium_Tablet",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Female_Standard_Laptop",
    "Italy_Male_Basic_Laptop",
    "United States_Male_Premium_Tablet",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Premium_Tablet",
    "Germany_Male_Basic_Tablet",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Standard_Laptop",
    "Italy_Female_Basic_Smart TV",
    "United States_Male_Premium_Smart TV",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Premium_Laptop",
    "Germany_Female_Basic_Smart TV",
    "France_Female_Premium_Smartphone",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Female_Standard_Smart TV",
    "Italy_Male_Basic_Tablet",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Female_Premium_Smartphone",
    "Germany_Male_Basic_Tablet",
    "France_Female_Basic_Smartphone",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Premium_Laptop",
    "Italy_Male_Basic_Laptop",
    "United States_Female_Basic_Laptop",
    "Canada_Female_Premium_Laptop",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Standard_Tablet",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Tablet",
    "Brazil_Male_Standard_Smart TV",
    "Mexico_Male_Basic_Tablet",
    "Spain_Female_Standard_Tablet",
    "Italy_Female_Premium_Smart TV",
    "United States_Male_Basic_Smart TV",
    "Canada_Male_Premium_Smartphone",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Basic_Laptop",
    "Germany_Male_Standard_Laptop",
    "France_Male_Premium_Laptop",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Female_Premium_Tablet",
    "Italy_Female_Basic_Tablet",
    "United States_Male_Premium_Tablet",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Standard_Smartphone",
    "Germany_Female_Basic_Smart TV",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Male_Standard_Laptop",
    "Spain_Female_Premium_Smartphone",
    "Italy_Female_Basic_Laptop",
    "United States_Male_Premium_Smart TV",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Standard_Smartphone",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Premium_Tablet",
    "Italy_Female_Basic_Smart TV",
    "United States_Female_Premium_Smartphone",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Standard_Smart TV",
    "Germany_Male_Basic_Smartphone",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Female_Premium_Laptop",
    "Italy_Male_Basic_Laptop",
    "Spain_Male_Premium_Smartphone",
    "Spain_Male_Basic_Smartphone",
    "United States_Male_Standard_Tablet",
    "Canada_Female_Standard_Laptop",
    "United States_Male_Basic_Smartphone",
    "United States_Male_Premium_Smart TV",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Premium_Smartphone",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Smart TV",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Male_Standard_Tablet",
    "Spain_Male_Standard_Tablet",
    "Italy_Female_Basic_Laptop",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Basic_Smart TV",
    "United States_Female_Standard_Tablet",
    "Canada_Male_Premium_Smartphone",
    "United States_Male_Basic_Smart TV",
    "United States_Female_Basic_Smart TV",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Premium_Tablet",
    "Germany_Male_Basic_Tablet",
    "France_Male_Basic_Laptop",
    "Brazil_Female_Premium_Tablet",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Female_Standard_Laptop",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Standard_Laptop",
    "United States_Male_Basic_Smartphone",
    "Canada_Female_Standard_Smart TV",
    "United States_Female_Premium_Laptop",
    "United States_Male_Basic_Smart TV",
    "Canada_Male_Premium_Smartphone",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Basic_Tablet",
    "Germany_Male_Standard_Smartphone",
    "France_Male_Premium_Smart TV",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Premium_Tablet",
    "Italy_Male_Basic_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Spain_Male_Basic_Tablet",
    "United States_Female_Standard_Smartphone",
    "Canada_Female_Standard_Smartphone",
    "United States_Female_Basic_Tablet",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Smartphone",
    "Germany_Female_Basic_Smartphone",
    "France_Male_Premium_Smartphone",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Female_Standard_Tablet",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Basic_Laptop",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Premium_Smartphone",
    "United States_Male_Basic_Laptop",
    "United States_Male_Premium_Tablet",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Female_Standard_Laptop",
    "Germany_Female_Basic_Laptop",
    "France_Male_Premium_Smart TV",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Female_Premium_Smartphone",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Tablet",
    "Spain_Male_Basic_Laptop",
    "United States_Female_Standard_Laptop",
    "Canada_Female_Standard_Tablet",
    "United States_Female_Basic_Tablet",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Premium_Smart TV",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Standard_Laptop",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Basic_Smartphone",
    "United States_Male_Standard_Smartphone",
    "Canada_Female_Premium_Smart TV",
    "United States_Male_Basic_Laptop",
    "United States_Female_Basic_Smart TV",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Premium_Smart TV",
    "Germany_Female_Basic_Smart TV",
    "France_Female_Basic_Smart TV",
    "Brazil_Male_Premium_Smartphone",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Standard_Smartphone",
    "Italy_Female_Basic_Tablet",
    "Spain_Male_Premium_Tablet",
    "Spain_Female_Standard_Smart TV",
    "United States_Female_Basic_Smart TV",
    "Canada_Female_Standard_Smartphone",
    "United States_Female_Premium_Tablet",
    "United States_Female_Basic_Smartphone",
    "Canada_Male_Premium_Smart TV",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Basic_Smartphone",
    "Germany_Male_Standard_Smart TV",
    "France_Female_Premium_Laptop",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Premium_Smartphone",
    "Italy_Female_Basic_Smartphone",
    "Spain_Male_Premium_Smart TV",
    "Spain_Male_Basic_Smartphone",
    "United States_Female_Standard_Smart TV",
    "Canada_Male_Standard_Smartphone",
    "United States_Male_Basic_Tablet",
    "United States_Male_Premium_Laptop",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Premium_Tablet",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Smartphone",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Female_Standard_Smart TV",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Tablet",
    "Canada_Female_Premium_Laptop",
    "United States_Female_Basic_Laptop",
    "United States_Male_Premium_Tablet",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Standard_Laptop",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Female_Premium_Smartphone",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Tablet",
    "Spain_Female_Basic_Smartphone",
    "United States_Female_Standard_Smartphone",
    "Canada_Female_Standard_Smartphone",
    "United States_Male_Basic_Tablet",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Premium_Laptop",
    "Germany_Male_Basic_Smart TV",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Male_Standard_Tablet",
    "Spain_Male_Standard_Smart TV",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Basic_Smartphone",
    "United States_Male_Standard_Smart TV",
    "Canada_Female_Premium_Tablet",
    "United States_Male_Basic_Smart TV",
    "United States_Male_Basic_Tablet",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Premium_Laptop",
    "Germany_Female_Basic_Tablet",
    "France_Male_Basic_Smartphone",
    "Brazil_Male_Premium_Smart TV",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Standard_Laptop",
    "Italy_Female_Basic_Laptop",
    "Spain_Male_Premium_Laptop",
    "Spain_Male_Standard_Tablet",
    "United States_Male_Basic_Smartphone",
    "Canada_Male_Standard_Smartphone",
    "United States_Male_Premium_Smartphone",
    "United States_Male_Basic_Tablet",
    "Canada_Female_Premium_Tablet",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Basic_Smart TV",
    "Germany_Male_Standard_Laptop",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Premium_Smart TV",
    "Italy_Male_Basic_Laptop",
    "Spain_Male_Premium_Tablet",
    "Spain_Male_Basic_Smart TV",
    "United States_Male_Standard_Laptop",
    "Canada_Female_Standard_Smartphone",
    "United States_Female_Basic_Laptop",
    "United States_Male_Premium_Smart TV",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Premium_Tablet",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Smartphone",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Male_Standard_Laptop",
    "Spain_Female_Standard_Smart TV",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Basic_Tablet",
    "United States_Male_Standard_Laptop",
    "Canada_Male_Premium_Tablet",
    "United States_Female_Basic_Laptop",
    "United States_Male_Premium_Laptop",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Standard_Tablet",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Tablet",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Male_Premium_Laptop",
    "Italy_Female_Basic_Tablet",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Basic_Laptop",
    "United States_Male_Standard_Laptop",
    "Canada_Female_Standard_Smartphone",
    "United States_Female_Basic_Smartphone",
    "United States_Male_Premium_Tablet",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Premium_Tablet",
    "Germany_Male_Basic_Laptop",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Male_Standard_Smartphone",
    "Italy_Male_Basic_Tablet",
    "Spain_Male_Premium_Smart TV",
    "Spain_Male_Basic_Smartphone",
    "United States_Female_Standard_Laptop",
    "Canada_Female_Premium_Tablet",
    "United States_Female_Basic_Laptop",
    "United States_Male_Basic_Smartphone",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Smart TV",
    "France_Female_Basic_Laptop",
    "Brazil_Female_Premium_Smartphone",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Male_Standard_Laptop",
    "Italy_Male_Basic_Tablet",
    "Spain_Female_Premium_Smartphone",
    "Spain_Male_Standard_Laptop",
    "United States_Male_Basic_Laptop",
    "Canada_Male_Standard_Smart TV",
    "United States_Female_Premium_Smartphone",
    "United States_Female_Basic_Smart TV",
    "Canada_Male_Premium_Laptop",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Basic_Smart TV",
    "Germany_Female_Standard_Smart TV",
    "France_Male_Premium_Smartphone",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Premium_Smart TV",
    "Italy_Female_Basic_Laptop",
    "Spain_Male_Premium_Tablet",
    "Spain_Male_Basic_Laptop",
    "United States_Female_Standard_Smart TV",
    "Canada_Male_Standard_Smartphone",
    "United States_Male_Basic_Tablet",
    "United States_Male_Premium_Laptop",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Premium_Smart TV",
    "Germany_Female_Basic_Laptop",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Female_Standard_Laptop",
    "Spain_Male_Standard_Laptop",
    "Italy_Female_Basic_Laptop",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Laptop",
    "United States_Female_Standard_Tablet",
    "Canada_Female_Premium_Smartphone",
    "United States_Female_Basic_Smartphone",
    "United States_Male_Premium_Smartphone",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Standard_Smart TV",
    "Germany_Male_Basic_Smartphone",
    "France_Male_Premium_Smart TV",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Premium_Tablet",
    "Italy_Male_Basic_Smartphone",
    "Spain_Male_Premium_Smartphone",
    "Spain_Female_Basic_Smartphone",
    "United States_Male_Standard_Smart TV",
    "Canada_Female_Standard_Smartphone",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Smartphone",
    "Germany_Male_Basic_Smartphone",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Standard_Smartphone",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Premium_Laptop",
    "United States_Female_Basic_Tablet",
    "United States_Female_Basic_Laptop",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Premium_Smartphone",
    "Germany_Female_Basic_Laptop",
    "France_Male_Basic_Smart TV",
    "Brazil_Male_Premium_Smartphone",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Standard_Tablet",
    "Italy_Female_Basic_Smartphone",
    "Spain_Male_Premium_Smartphone",
    "Spain_Female_Standard_Tablet",
    "United States_Male_Basic_Smartphone",
    "Canada_Female_Standard_Smart TV",
    "United States_Male_Premium_Laptop",
    "United States_Male_Basic_Laptop",
    "Canada_Female_Premium_Smart TV",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Basic_Laptop",
    "Germany_Male_Standard_Smartphone",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Italy_Male_Basic_Smartphone",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Basic_Smart TV",
    "United States_Male_Standard_Tablet",
    "Canada_Female_Standard_Smart TV",
    "United States_Female_Basic_Smart TV",
    "United States_Male_Premium_Laptop",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Smart TV",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Standard_Tablet",
    "Italy_Male_Basic_Smart TV",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Basic_Smartphone",
    "United States_Male_Standard_Laptop",
    "Canada_Male_Premium_Tablet",
    "United States_Male_Basic_Smartphone",
    "United States_Female_Premium_Smart TV",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Standard_Tablet",
    "Germany_Male_Basic_Laptop",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Italy_Male_Basic_Smart TV",
    "Spain_Male_Premium_Tablet",
    "Spain_Male_Basic_Smart TV",
    "United States_Male_Standard_Smartphone",
    "Canada_Female_Standard_Tablet",
    "United States_Male_Basic_Smart TV",
    "United States_Female_Premium_Smartphone",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Premium_Tablet",
    "Germany_Male_Basic_Tablet",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Standard_Smartphone",
    "Italy_Male_Basic_Smart TV",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Basic_Tablet",
    "United States_Female_Standard_Smart TV",
    "Canada_Male_Premium_Smart TV",
    "United States_Male_Basic_Smartphone",
    "United States_Female_Basic_Smartphone",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Premium_Laptop",
    "Germany_Female_Basic_Smartphone",
    "France_Male_Basic_Smartphone",
    "Brazil_Male_Premium_Tablet",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Standard_Tablet",
    "Italy_Female_Basic_Laptop",
    "Spain_Male_Premium_Smart TV",
    "Spain_Male_Standard_Laptop",
    "United States_Female_Basic_Smart TV",
    "Canada_Male_Standard_Tablet",
    "United States_Female_Premium_Smart TV",
    "United States_Male_Basic_Smart TV",
    "Canada_Male_Premium_Tablet",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Basic_Smart TV",
    "Germany_Male_Standard_Laptop",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Premium_Smartphone",
    "Italy_Female_Basic_Tablet",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Basic_Tablet",
    "United States_Male_Standard_Tablet",
    "Canada_Female_Standard_Smart TV",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Laptop",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Male_Standard_Laptop",
    "Spain_Female_Standard_Smartphone",
    "Italy_Male_Basic_Smartphone",
    "Spain_Male_Premium_Tablet",
    "Spain_Male_Basic_Smartphone",
    "United States_Male_Standard_Smart TV",
    "Canada_Male_Premium_Tablet",
    "United States_Female_Basic_Smart TV",
    "United States_Male_Premium_Smart TV",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Standard_Tablet",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Laptop",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Premium_Tablet",
    "Italy_Male_Basic_Tablet",
    "Spain_Female_Premium_Smartphone",
    "Spain_Female_Basic_Tablet",
    "United States_Female_Standard_Laptop",
    "Canada_Male_Standard_Smartphone",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Smart TV",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Female_Premium_Laptop",
    "Germany_Female_Basic_Tablet",
    "France_Male_Premium_Laptop",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Standard_Smart TV",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Laptop",
    "Spain_Female_Basic_Smartphone",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Premium_Smart TV",
    "United States_Female_Basic_Tablet",
    "United States_Male_Basic_Tablet",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Premium_Smartphone",
    "Germany_Female_Basic_Smart TV",
    "France_Female_Basic_Laptop",
    "Brazil_Female_Premium_Laptop",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Male_Standard_Smartphone",
    "Italy_Male_Basic_Smart TV",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Standard_Smart TV",
    "United States_Female_Basic_Smartphone",
    "Canada_Male_Standard_Smart TV",
    "United States_Male_Premium_Smart TV",
    "United States_Male_Basic_Laptop",
    "Canada_Female_Premium_Tablet",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Basic_Smartphone",
    "Germany_Male_Standard_Smartphone",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Laptop",
    "Spain_Male_Premium_Tablet",
    "Italy_Female_Basic_Tablet",
    "Spain_Male_Premium_Tablet",
    "Spain_Male_Basic_Tablet",
    "United States_Female_Standard_Laptop",
    "Canada_Female_Standard_Tablet",
    "United States_Female_Basic_Smartphone",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Smart TV",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Female_Standard_Laptop",
    "Italy_Female_Basic_Tablet",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Smartphone",
    "United States_Female_Standard_Smart TV",
    "Canada_Female_Premium_Smartphone",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Tablet",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Standard_Tablet",
    "Germany_Male_Basic_Tablet",
    "France_Male_Premium_Smart TV",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Premium_Smartphone",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Laptop",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Standard_Smartphone",
    "United States_Male_Basic_Smartphone",
    "United States_Female_Premium_Smart TV",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Premium_Tablet",
    "Germany_Male_Basic_Smartphone",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Standard_Laptop",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Laptop",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Premium_Tablet",
    "United States_Male_Basic_Tablet",
    "United States_Male_Basic_Laptop",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Male_Premium_Smartphone",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Basic_Laptop",
    "Brazil_Male_Premium_Tablet",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Standard_Tablet",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Standard_Tablet",
    "United States_Female_Basic_Smart TV",
    "Canada_Male_Standard_Tablet",
    "United States_Female_Premium_Laptop",
    "United States_Female_Basic_Tablet",
    "Canada_Female_Premium_Laptop",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Basic_Tablet",
    "Germany_Male_Standard_Smart TV",
    "France_Male_Premium_Laptop",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Premium_Smart TV",
    "Italy_Male_Basic_Tablet",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Smart TV",
    "Canada_Female_Standard_Smartphone",
    "United States_Male_Basic_Smart TV",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Premium_Tablet",
    "Germany_Male_Basic_Smartphone",
    "France_Female_Premium_Smartphone",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Female_Standard_Laptop",
    "Spain_Male_Standard_Smartphone",
    "Italy_Female_Basic_Smartphone",
    "Spain_Female_Premium_Tablet",
    "Spain_Male_Basic_Tablet",
    "United States_Female_Standard_Smartphone",
    "Canada_Female_Premium_Tablet",
    "United States_Male_Basic_Smart TV",
    "United States_Female_Premium_Smartphone",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Standard_Tablet",
    "Germany_Male_Basic_Smartphone",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Female_Premium_Laptop",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Basic_Smartphone",
    "United States_Female_Standard_Tablet",
    "Canada_Female_Standard_Smart TV",
    "United States_Male_Basic_Tablet",
    "United States_Male_Premium_Smart TV",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Premium_Smartphone",
    "Germany_Female_Basic_Tablet",
    "France_Male_Premium_Smart TV",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Standard_Smart TV",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Laptop",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Smart TV",
    "Canada_Male_Premium_Smartphone",
    "United States_Female_Basic_Smartphone",
    "United States_Female_Basic_Smart TV",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Premium_Laptop",
    "Germany_Female_Basic_Tablet",
    "France_Female_Basic_Laptop",
    "Brazil_Female_Premium_Tablet",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Standard_Smartphone",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Standard_Laptop",
    "United States_Male_Basic_Laptop",
    "Canada_Female_Standard_Smart TV",
    "United States_Male_Premium_Laptop",
    "United States_Male_Basic_Smartphone",
    "Canada_Male_Premium_Smart TV",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Basic_Smartphone",
    "Germany_Female_Standard_Smart TV",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Male_Premium_Tablet",
    "Italy_Male_Basic_Smart TV",
    "Spain_Female_Premium_Smartphone",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Smartphone",
    "Canada_Female_Standard_Tablet",
    "United States_Male_Basic_Tablet",
    "United States_Male_Premium_Laptop",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Female_Premium_Laptop",
    "Germany_Female_Basic_Laptop",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Standard_Laptop",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Smartphone",
    "Spain_Male_Basic_Smart TV",
    "United States_Female_Standard_Smart TV",
    "Canada_Male_Premium_Smart TV",
    "United States_Male_Basic_Smartphone",
    "United States_Female_Premium_Tablet",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Standard_Smartphone",
    "Germany_Male_Basic_Smart TV",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Premium_Laptop",
    "Italy_Male_Basic_Laptop",
    "Spain_Male_Premium_Smart TV",
    "Spain_Male_Basic_Tablet",
    "United States_Male_Standard_Smart TV",
    "Canada_Female_Standard_Smartphone",
    "United States_Female_Basic_Smart TV",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Premium_Laptop",
    "Germany_Male_Basic_Smart TV",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Male_Standard_Tablet",
    "Spain_Male_Standard_Smartphone",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Smartphone",
    "Spain_Male_Basic_Laptop",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Premium_Smart TV",
    "United States_Female_Basic_Smart TV",
    "United States_Female_Basic_Tablet",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Female_Premium_Smart TV",
    "Germany_Male_Basic_Smartphone",
    "France_Male_Basic_Smart TV",
    "Brazil_Male_Premium_Smart TV",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Male_Standard_Laptop",
    "Italy_Female_Basic_Laptop",
    "Spain_Male_Premium_Smart TV",
    "Spain_Male_Standard_Smart TV",
    "United States_Male_Basic_Smartphone",
    "Canada_Male_Standard_Tablet",
    "United States_Male_Premium_Smart TV",
    "United States_Female_Basic_Laptop",
    "Canada_Female_Premium_Tablet",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Female_Basic_Smartphone",
    "Germany_Female_Standard_Laptop",
    "France_Female_Premium_Tablet",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Male_Standard_Laptop",
    "Spain_Female_Premium_Smartphone",
    "Italy_Male_Basic_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Smartphone",
    "Canada_Female_Standard_Smartphone",
    "United States_Female_Basic_Smart TV",
    "United States_Male_Premium_Smartphone",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Premium_Smartphone",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Female_Standard_Smartphone",
    "Italy_Female_Basic_Tablet",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Basic_Tablet",
    "United States_Female_Standard_Smartphone",
    "Canada_Male_Premium_Laptop",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Standard_Tablet",
    "Germany_Female_Basic_Smartphone",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Female_Premium_Smart TV",
    "Italy_Female_Basic_Smartphone",
    "Spain_Female_Premium_Tablet",
    "Spain_Male_Basic_Laptop",
    "United States_Male_Standard_Laptop",
    "Canada_Female_Standard_Tablet",
    "United States_Male_Basic_Smart TV",
    "United States_Male_Premium_Laptop",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Premium_Laptop",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Smart TV",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Tablet",
    "Spain_Female_Standard_Smart TV",
    "Italy_Female_Basic_Tablet",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Basic_Tablet",
    "United States_Female_Standard_Laptop",
    "Canada_Female_Premium_Smartphone",
    "United States_Female_Basic_Smart TV",
    "United States_Male_Basic_Smartphone",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Premium_Smart TV",
    "Germany_Female_Basic_Smartphone",
    "France_Female_Basic_Laptop",
    "Brazil_Male_Premium_Smartphone",
    "Mexico_Male_Standard_Laptop",
    "Spain_Female_Standard_Tablet",
    "Italy_Female_Basic_Laptop",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Standard_Tablet",
    "United States_Male_Basic_Laptop",
    "Canada_Female_Standard_Tablet",
    "United States_Male_Premium_Smart TV",
    "United States_Male_Basic_Laptop",
    "Canada_Male_Premium_Tablet",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Basic_Tablet",
    "Germany_Male_Standard_Laptop",
    "France_Female_Premium_Laptop",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Female_Standard_Tablet",
    "Spain_Female_Premium_Smartphone",
    "Italy_Female_Basic_Smartphone",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Smartphone",
    "United States_Male_Standard_Laptop",
    "Canada_Male_Standard_Smart TV",
    "United States_Male_Basic_Laptop",
    "United States_Male_Premium_Smart TV",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Premium_Laptop",
    "Germany_Male_Basic_Smartphone",
    "France_Female_Premium_Laptop",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Standard_Tablet",
    "Italy_Male_Basic_Laptop",
    "Spain_Male_Premium_Tablet",
    "Spain_Female_Basic_Laptop",
    "United States_Male_Standard_Smart TV",
    "Canada_Male_Premium_Tablet",
    "United States_Male_Basic_Smartphone",
    "United States_Female_Premium_Tablet",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Standard_Smartphone",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Tablet",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Italy_Male_Basic_Smartphone",
    "Spain_Male_Premium_Smartphone",
    "Spain_Male_Basic_Laptop",
    "United States_Female_Standard_Tablet",
    "Canada_Male_Standard_Laptop",
    "United States_Female_Basic_Smart TV",
    "United States_Male_Premium_Smartphone",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Tablet",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Female_Standard_Laptop",
    "Spain_Male_Standard_Laptop",
    "Italy_Female_Basic_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Basic_Laptop",
    "United States_Male_Standard_Tablet",
    "Canada_Female_Premium_Smartphone",
    "United States_Male_Basic_Smart TV",
    "United States_Female_Basic_Smart TV",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Premium_Laptop",
    "Germany_Female_Basic_Smartphone",
    "France_Female_Basic_Laptop",
    "Brazil_Male_Premium_Laptop",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Standard_Tablet",
    "Italy_Male_Basic_Tablet",
    "Spain_Male_Premium_Smartphone",
    "Spain_Male_Standard_Smart TV",
    "United States_Male_Basic_Tablet",
    "Canada_Male_Standard_Laptop",
    "United States_Male_Premium_Smart TV",
    "United States_Female_Basic_Laptop",
    "Canada_Female_Premium_Laptop",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Basic_Tablet",
    "Germany_Female_Standard_Smartphone",
    "France_Male_Premium_Laptop",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Premium_Laptop",
    "Italy_Female_Basic_Tablet",
    "Spain_Female_Premium_Laptop",
    "Spain_Female_Basic_Laptop",
    "United States_Female_Standard_Laptop",
    "Canada_Male_Standard_Smart TV",
    "United States_Male_Basic_Laptop",
    "United States_Male_Premium_Tablet",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Female_Premium_Smartphone",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Standard_Smart TV",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Basic_Smart TV",
    "United States_Male_Standard_Smartphone",
    "Canada_Male_Premium_Smartphone",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Tablet",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Female_Standard_Tablet",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Female_Premium_Smart TV",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Basic_Laptop",
    "United States_Male_Standard_Laptop",
    "Canada_Female_Standard_Tablet",
    "United States_Female_Basic_Smart TV",
    "United States_Female_Premium_Smart TV",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Premium_Tablet",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Smart TV",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Standard_Tablet",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Tablet",
    "United States_Female_Standard_Smart TV",
    "Canada_Male_Premium_Smartphone",
    "United States_Female_Basic_Smartphone",
    "United States_Female_Basic_Smart TV",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Laptop",
    "Germany_Male_Basic_Smartphone",
    "France_Female_Basic_Smart TV",
    "Brazil_Male_Premium_Tablet",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Male_Standard_Laptop",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Laptop",
    "Spain_Male_Standard_Smartphone",
    "United States_Female_Basic_Tablet",
    "Canada_Female_Standard_Laptop",
    "United States_Male_Premium_Smartphone",
    "United States_Female_Basic_Smart TV",
    "Canada_Male_Premium_Laptop",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Basic_Laptop",
    "Germany_Female_Standard_Smart TV",
    "France_Female_Premium_Tablet",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Premium_Tablet",
    "Italy_Male_Basic_Smartphone",
    "Spain_Male_Premium_Tablet",
    "Spain_Female_Basic_Tablet",
    "United States_Female_Standard_Laptop",
    "Canada_Female_Standard_Laptop",
    "United States_Female_Basic_Smartphone",
    "United States_Female_Premium_Tablet",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Premium_Smartphone",
    "Germany_Male_Basic_Smart TV",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Female_Standard_Tablet",
    "Spain_Female_Standard_Laptop",
    "Italy_Male_Basic_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Smartphone",
    "United States_Male_Standard_Smart TV",
    "Canada_Male_Premium_Laptop",
    "United States_Male_Basic_Laptop",
    "United States_Female_Premium_Smart TV",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Standard_Smart TV",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Premium_Laptop",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Tablet",
    "Spain_Male_Basic_Smart TV",
    "United States_Female_Standard_Smart TV",
    "Canada_Female_Standard_Smart TV",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Laptop",
    "France_Male_Premium_Smartphone",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Standard_Smart TV",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Laptop",
    "Spain_Female_Basic_Laptop",
    "United States_Female_Standard_Laptop",
    "Canada_Female_Premium_Smartphone",
    "United States_Female_Basic_Tablet",
    "United States_Male_Basic_Tablet",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Premium_Smart TV",
    "Germany_Female_Basic_Tablet",
    "France_Male_Basic_Smart TV",
    "Brazil_Female_Premium_Laptop",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Standard_Smart TV",
    "Italy_Male_Basic_Laptop",
    "Spain_Male_Premium_Smartphone",
    "Spain_Female_Standard_Tablet",
    "United States_Male_Basic_Laptop",
    "Canada_Male_Standard_Smartphone",
    "United States_Male_Premium_Smart TV",
    "United States_Male_Basic_Smart TV",
    "Canada_Female_Premium_Smart TV",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Basic_Smartphone",
    "Germany_Male_Standard_Smart TV",
    "France_Male_Premium_Laptop",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Male_Premium_Tablet",
    "Italy_Female_Basic_Smartphone",
    "Spain_Male_Premium_Tablet",
    "Spain_Female_Basic_Laptop",
    "United States_Male_Standard_Smart TV",
    "Canada_Male_Standard_Smartphone",
    "United States_Female_Basic_Tablet",
    "United States_Male_Premium_Tablet",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Female_Premium_Laptop",
    "Germany_Male_Basic_Smartphone",
    "France_Female_Premium_Tablet",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Standard_Tablet",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Basic_Tablet",
    "United States_Female_Standard_Smart TV",
    "Canada_Male_Premium_Laptop",
    "United States_Male_Basic_Laptop",
    "United States_Male_Premium_Smartphone",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Standard_Tablet",
    "Germany_Female_Basic_Laptop",
    "France_Male_Premium_Smart TV",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Male_Standard_Tablet",
    "Spain_Male_Premium_Tablet",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Tablet",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Tablet",
    "Canada_Female_Standard_Laptop",
    "United States_Female_Basic_Smartphone",
    "United States_Female_Premium_Smartphone",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Premium_Tablet",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Male_Standard_Laptop",
    "Spain_Female_Standard_Tablet",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Laptop",
    "Spain_Male_Basic_Smartphone",
    "United States_Female_Standard_Smart TV",
    "Canada_Male_Premium_Tablet",
    "United States_Male_Basic_Tablet",
    "United States_Male_Basic_Tablet",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Smart TV",
    "Germany_Female_Basic_Laptop",
    "France_Female_Basic_Smartphone",
    "Brazil_Male_Premium_Tablet",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Standard_Smart TV",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Standard_Smart TV",
    "United States_Male_Basic_Tablet",
    "Canada_Male_Standard_Tablet",
    "United States_Male_Premium_Laptop",
    "United States_Female_Basic_Tablet",
    "Canada_Male_Premium_Tablet",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Basic_Tablet",
    "Germany_Female_Standard_Smart TV",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Premium_Tablet",
    "Italy_Female_Basic_Tablet",
    "Spain_Male_Premium_Laptop",
    "Spain_Male_Basic_Smart TV",
    "United States_Male_Standard_Laptop",
    "Canada_Female_Standard_Smart TV",
    "United States_Male_Basic_Tablet",
    "United States_Male_Premium_Smartphone",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Premium_Smartphone",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Female_Standard_Smart TV",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Basic_Smartphone",
    "United States_Female_Standard_Smartphone",
    "Canada_Female_Premium_Tablet",
    "United States_Female_Basic_Smart TV",
    "United States_Male_Premium_Laptop",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Female_Standard_Laptop",
    "Germany_Male_Basic_Smartphone",
    "France_Male_Premium_Laptop",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Premium_Smartphone",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Smartphone",
    "United States_Female_Standard_Laptop",
    "Canada_Male_Standard_Smart TV",
    "United States_Male_Basic_Smart TV",
    "United States_Male_Premium_Laptop",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Tablet",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Standard_Laptop",
    "Italy_Male_Basic_Smart TV",
    "Spain_Male_Premium_Tablet",
    "Spain_Male_Basic_Tablet",
    "United States_Female_Standard_Tablet",
    "Canada_Male_Premium_Smartphone",
    "United States_Female_Basic_Laptop",
    "United States_Female_Basic_Tablet",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Premium_Tablet",
    "Germany_Male_Basic_Tablet",
    "France_Male_Basic_Smart TV",
    "Brazil_Male_Premium_Tablet",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Standard_Tablet",
    "Italy_Female_Basic_Tablet",
    "Spain_Male_Premium_Smartphone",
    "Spain_Male_Standard_Smartphone",
    "United States_Female_Basic_Laptop",
    "Canada_Male_Standard_Smartphone",
    "United States_Male_Premium_Tablet",
    "United States_Female_Basic_Laptop",
    "Canada_Male_Premium_Smartphone",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Basic_Laptop",
    "Germany_Male_Standard_Smartphone",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Premium_Tablet",
    "Italy_Male_Basic_Tablet",
    "Spain_Female_Premium_Smartphone",
    "Spain_Male_Basic_Tablet",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Standard_Smart TV",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Premium_Tablet",
    "Germany_Male_Basic_Laptop",
    "France_Male_Premium_Smart TV",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Standard_Smartphone",
    "Italy_Male_Basic_Laptop",
    "Spain_Male_Premium_Laptop",
    "Spain_Male_Basic_Smartphone",
    "United States_Female_Standard_Tablet",
    "Canada_Male_Premium_Tablet",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Smart TV",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Standard_Laptop",
    "Germany_Female_Basic_Smartphone",
    "France_Male_Premium_Laptop",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Premium_Laptop",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Spain_Male_Basic_Smartphone",
    "United States_Male_Standard_Smart TV",
    "Canada_Male_Standard_Laptop",
    "United States_Female_Basic_Tablet",
    "United States_Male_Premium_Laptop",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Premium_Smartphone",
    "Germany_Male_Basic_Smart TV",
    "France_Male_Premium_Smartphone",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Tablet",
    "Spain_Female_Standard_Tablet",
    "Italy_Female_Basic_Laptop",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Smartphone",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Premium_Laptop",
    "United States_Female_Basic_Tablet",
    "United States_Male_Basic_Tablet",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Laptop",
    "Germany_Female_Basic_Smartphone",
    "France_Female_Basic_Laptop",
    "Brazil_Male_Premium_Smartphone",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Standard_Laptop",
    "Italy_Female_Basic_Smartphone",
    "Spain_Male_Premium_Tablet",
    "Spain_Male_Standard_Smartphone",
    "United States_Female_Basic_Tablet",
    "Canada_Male_Standard_Tablet",
    "United States_Male_Premium_Smartphone",
    "United States_Female_Basic_Smartphone",
    "Canada_Female_Premium_Laptop",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Basic_Smartphone",
    "Germany_Female_Standard_Laptop",
    "France_Male_Premium_Smartphone",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Premium_Smart TV",
    "Italy_Male_Basic_Tablet",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Laptop",
    "United States_Male_Standard_Smartphone",
    "Canada_Female_Standard_Laptop",
    "United States_Female_Basic_Smartphone",
    "United States_Female_Premium_Tablet",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Laptop",
    "France_Male_Premium_Tablet",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Standard_Smart TV",
    "Italy_Male_Basic_Tablet",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Smartphone",
    "United States_Female_Standard_Smartphone",
    "Canada_Female_Premium_Tablet",
    "United States_Female_Basic_Tablet",
    "United States_Female_Premium_Smart TV",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Standard_Laptop",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Premium_Tablet",
    "Italy_Male_Basic_Tablet",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Basic_Tablet",
    "United States_Female_Standard_Tablet",
    "Canada_Female_Standard_Smartphone",
    "United States_Male_Basic_Smart TV",
    "United States_Female_Premium_Laptop",
    "Canada_Male_Basic_Laptop",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Premium_Tablet",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Female_Standard_Tablet",
    "Italy_Male_Basic_Smart TV",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Basic_Tablet",
    "United States_Female_Standard_Smart TV",
    "Canada_Female_Premium_Tablet",
    "United States_Male_Basic_Smart TV",
    "United States_Male_Basic_Tablet",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Premium_Tablet",
    "Germany_Male_Basic_Tablet",
    "France_Male_Basic_Tablet",
    "Brazil_Male_Premium_Smartphone",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Female_Standard_Laptop",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Standard_Smartphone",
    "United States_Male_Basic_Laptop",
    "Canada_Female_Standard_Tablet",
    "United States_Male_Premium_Laptop",
    "United States_Male_Basic_Smart TV",
    "Canada_Male_Premium_Smartphone",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Basic_Smartphone",
    "Germany_Female_Standard_Tablet",
    "France_Female_Premium_Laptop",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Female_Premium_Tablet",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Smartphone",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Tablet",
    "Canada_Female_Standard_Laptop",
    "United States_Male_Basic_Smart TV",
    "United States_Male_Premium_Tablet",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Premium_Tablet",
    "Germany_Female_Basic_Smartphone",
    "France_Male_Premium_Laptop",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Male_Standard_Smart TV",
    "Italy_Female_Basic_Tablet",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Basic_Smartphone",
    "United States_Female_Standard_Smartphone",
    "Canada_Female_Premium_Smart TV",
    "United States_Male_Basic_Laptop",
    "United States_Female_Premium_Tablet",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Standard_Smart TV",
    "Germany_Female_Basic_Smartphone",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Male_Standard_Laptop",
    "Spain_Female_Premium_Smartphone",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Laptop",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Laptop",
    "Canada_Female_Standard_Laptop",
    "United States_Male_Basic_Smartphone",
    "United States_Female_Premium_Smartphone",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Laptop",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Laptop",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Male_Standard_Smartphone",
    "Italy_Male_Basic_Smartphone",
    "Spain_Male_Premium_Laptop",
    "Spain_Male_Basic_Tablet",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Premium_Smart TV",
    "United States_Male_Basic_Tablet",
    "United States_Female_Basic_Smart TV",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Premium_Smartphone",
    "Germany_Male_Basic_Smart TV",
    "France_Male_Basic_Tablet",
    "Brazil_Female_Premium_Smartphone",
    "Mexico_Female_Standard_Tablet",
    "Spain_Female_Standard_Smart TV",
    "Italy_Male_Basic_Smart TV",
    "Spain_Male_Premium_Tablet",
    "Spain_Male_Standard_Smartphone",
    "United States_Female_Basic_Tablet",
    "Canada_Female_Standard_Tablet",
    "United States_Female_Premium_Tablet",
    "United States_Male_Basic_Smart TV",
    "Canada_Male_Premium_Smart TV",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Basic_Laptop",
    "Germany_Female_Standard_Laptop",
    "France_Female_Premium_Tablet",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Premium_Tablet",
    "Italy_Male_Basic_Laptop",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Basic_Smartphone",
    "United States_Female_Standard_Tablet",
    "Canada_Female_Standard_Smartphone",
    "United States_Female_Basic_Smartphone",
    "United States_Male_Premium_Tablet",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Female_Premium_Smartphone",
    "Germany_Female_Basic_Tablet",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Standard_Smart TV",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Basic_Laptop",
    "United States_Male_Standard_Tablet",
    "Canada_Female_Premium_Tablet",
    "United States_Male_Basic_Smartphone",
    "United States_Male_Premium_Tablet",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Standard_Smart TV",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Laptop",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Female_Premium_Laptop",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Basic_Smart TV",
    "United States_Female_Standard_Smart TV",
    "Canada_Female_Standard_Smartphone",
    "United States_Male_Basic_Smart TV",
    "United States_Male_Premium_Tablet",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Female_Premium_Laptop",
    "Germany_Female_Basic_Tablet",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Female_Standard_Tablet",
    "Italy_Male_Basic_Tablet",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Basic_Smart TV",
    "United States_Male_Standard_Smart TV",
    "Canada_Male_Premium_Tablet",
    "United States_Female_Basic_Smart TV",
    "United States_Female_Basic_Smart TV",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Female_Premium_Smart TV",
    "Germany_Female_Basic_Laptop",
    "France_Male_Basic_Tablet",
    "Brazil_Male_Premium_Smartphone",
    "Mexico_Male_Standard_Smartphone",
    "Spain_Male_Standard_Laptop",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Standard_Smartphone",
    "United States_Male_Basic_Tablet",
    "Canada_Female_Standard_Smartphone",
    "United States_Female_Premium_Laptop",
    "United States_Female_Basic_Smartphone",
    "Canada_Female_Premium_Tablet",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Basic_Smart TV",
    "Germany_Female_Standard_Tablet",
    "France_Female_Premium_Tablet",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Premium_Smartphone",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Basic_Tablet",
    "United States_Female_Standard_Tablet",
    "Canada_Male_Standard_Smartphone",
    "United States_Male_Basic_Tablet",
    "United States_Female_Premium_Tablet",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Female_Premium_Smartphone",
    "Germany_Female_Basic_Laptop",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Male_Standard_Tablet",
    "Spain_Male_Standard_Smartphone",
    "Italy_Male_Basic_Tablet",
    "Spain_Male_Premium_Smart TV",
    "Spain_Male_Basic_Smart TV",
    "United States_Female_Standard_Smartphone",
    "Canada_Female_Premium_Tablet",
    "United States_Male_Basic_Smart TV",
    "United States_Male_Premium_Laptop",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Standard_Laptop",
    "Germany_Male_Basic_Tablet",
    "France_Male_Premium_Smart TV",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Italy_Male_Basic_Smart TV",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Basic_Smartphone",
    "United States_Male_Standard_Tablet",
    "Canada_Female_Standard_Laptop",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Premium_Laptop",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Tablet",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Standard_Smart TV",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Basic_Laptop",
    "United States_Female_Standard_Laptop",
    "Canada_Female_Premium_Laptop",
    "United States_Male_Basic_Tablet",
    "United States_Female_Basic_Laptop",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Premium_Laptop",
    "Germany_Male_Basic_Laptop",
    "France_Male_Basic_Smart TV",
    "Brazil_Female_Premium_Smart TV",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Male_Standard_Smart TV",
    "Italy_Male_Basic_Tablet",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Standard_Smart TV",
    "United States_Male_Basic_Smartphone",
    "Canada_Male_Standard_Laptop",
    "United States_Female_Premium_Smart TV",
    "United States_Female_Basic_Smartphone",
    "Canada_Female_Premium_Smart TV",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Basic_Laptop",
    "Germany_Male_Standard_Laptop",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Italy_Female_Basic_Laptop",
    "Spain_Male_Premium_Smartphone",
    "Spain_Female_Basic_Laptop",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Standard_Tablet",
    "United States_Female_Basic_Smartphone",
    "United States_Male_Premium_Smartphone",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Premium_Tablet",
    "Germany_Female_Basic_Laptop",
    "France_Male_Premium_Tablet",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Male_Standard_Laptop",
    "Italy_Male_Basic_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Spain_Male_Basic_Tablet",
    "United States_Female_Standard_Smartphone",
    "Canada_Female_Premium_Tablet",
    "United States_Female_Basic_Tablet",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Standard_Smart TV",
    "Germany_Female_Basic_Smartphone",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Premium_Smartphone",
    "Italy_Female_Basic_Tablet",
    "Spain_Female_Premium_Laptop",
    "Spain_Female_Basic_Laptop",
    "United States_Male_Standard_Laptop",
    "Canada_Female_Standard_Smart TV",
    "United States_Female_Basic_Laptop",
    "United States_Male_Premium_Smart TV",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Premium_Smartphone",
    "Germany_Male_Basic_Laptop",
    "France_Female_Premium_Smart TV",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Standard_Tablet",
    "Italy_Female_Basic_Tablet",
    "Spain_Female_Premium_Smartphone",
    "Spain_Female_Basic_Laptop",
    "United States_Male_Standard_Smart TV",
    "Canada_Female_Premium_Smart TV",
    "United States_Male_Basic_Smart TV",
    "United States_Female_Basic_Tablet",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Premium_Laptop",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Basic_Tablet",
    "Brazil_Female_Premium_Smartphone",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Standard_Tablet",
    "Italy_Female_Basic_Smartphone",
    "Spain_Female_Premium_Smartphone",
    "Spain_Female_Standard_Smart TV",
    "United States_Female_Basic_Smartphone",
    "Canada_Male_Standard_Tablet",
    "United States_Female_Premium_Smartphone",
    "United States_Male_Basic_Laptop",
    "Canada_Female_Premium_Smart TV",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Basic_Tablet",
    "Germany_Female_Standard_Laptop",
    "France_Female_Premium_Tablet",
    "Brazil_Male_Basic_Laptop",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Male_Premium_Laptop",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Basic_Smart TV",
    "United States_Female_Standard_Tablet",
    "Canada_Male_Standard_Laptop",
    "United States_Female_Basic_Smartphone",
    "United States_Female_Premium_Smartphone",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Premium_Laptop",
    "Germany_Female_Basic_Tablet",
    "France_Male_Premium_Laptop",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Standard_Smart TV",
    "Italy_Female_Basic_Smartphone",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Smartphone",
    "Canada_Female_Premium_Smartphone",
    "United States_Male_Basic_Tablet",
    "United States_Female_Premium_Tablet",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Standard_Smartphone",
    "Germany_Female_Basic_Smart TV",
    "France_Female_Premium_Tablet",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Premium_Smart TV",
    "Italy_Female_Basic_Tablet",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Basic_Laptop",
    "United States_Male_Standard_Tablet",
    "Canada_Male_Standard_Smart TV",
    "United States_Male_Basic_Smartphone",
    "United States_Male_Premium_Smart TV",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Female_Premium_Tablet",
    "Germany_Female_Basic_Smartphone",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Female_Standard_Smartphone",
    "Italy_Male_Basic_Laptop",
    "Spain_Male_Premium_Smartphone",
    "Spain_Female_Basic_Laptop",
    "United States_Male_Standard_Smart TV",
    "Canada_Male_Premium_Tablet",
    "United States_Female_Basic_Smart TV",
    "United States_Male_Basic_Tablet",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Premium_Smartphone",
    "Germany_Male_Basic_Laptop",
    "France_Male_Basic_Tablet",
    "Brazil_Female_Premium_Tablet",
    "Mexico_Female_Standard_Tablet",
    "Spain_Male_Standard_Smart TV",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Standard_Tablet",
    "United States_Female_Basic_Smart TV",
    "Canada_Male_Standard_Tablet",
    "United States_Male_Premium_Smart TV",
    "United States_Male_Basic_Smart TV",
    "Canada_Male_Premium_Tablet",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Basic_Laptop",
    "Germany_Male_Standard_Tablet",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Male_Standard_Laptop",
    "Spain_Female_Premium_Smart TV",
    "Italy_Female_Basic_Smart TV",
    "Spain_Male_Premium_Smartphone",
    "Spain_Male_Basic_Smartphone",
    "United States_Female_Standard_Smart TV",
    "Canada_Male_Standard_Tablet",
    "United States_Male_Basic_Laptop",
    "United States_Male_Premium_Laptop",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Male_Standard_Smartphone",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Smart TV",
    "France_Male_Premium_Smart TV",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Laptop",
    "Spain_Female_Standard_Tablet",
    "Italy_Male_Basic_Smartphone",
    "Spain_Male_Premium_Laptop",
    "Spain_Male_Basic_Smart TV",
    "United States_Female_Standard_Tablet",
    "Canada_Female_Premium_Tablet",
    "United States_Female_Basic_Smartphone",
    "United States_Female_Premium_Smart TV",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Standard_Laptop",
    "Germany_Male_Basic_Smartphone",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Male_Standard_Laptop",
    "Spain_Male_Premium_Tablet",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Basic_Laptop",
    "United States_Male_Standard_Tablet",
    "Canada_Female_Standard_Smartphone",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Smartphone",
    "Canada_Female_Basic_Laptop",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Male_Premium_Tablet",
    "Germany_Male_Basic_Laptop",
    "France_Male_Premium_Smart TV",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Male_Standard_Smart TV",
    "Italy_Female_Basic_Laptop",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Basic_Smart TV",
    "United States_Female_Standard_Laptop",
    "Canada_Male_Premium_Smart TV",
    "United States_Female_Basic_Smart TV",
    "United States_Female_Basic_Smart TV",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Premium_Smartphone",
    "Germany_Male_Basic_Tablet",
    "France_Female_Basic_Laptop",
    "Brazil_Female_Premium_Tablet",
    "Mexico_Female_Standard_Laptop",
    "Spain_Male_Standard_Laptop",
    "Italy_Female_Basic_Laptop",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Standard_Laptop",
    "United States_Female_Basic_Laptop",
    "Canada_Female_Standard_Laptop",
    "United States_Male_Premium_Tablet",
    "United States_Female_Basic_Tablet",
    "Canada_Female_Premium_Smartphone",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Male_Basic_Smartphone",
    "Germany_Male_Standard_Tablet",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Female_Premium_Smartphone",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Laptop",
    "Spain_Male_Basic_Smart TV",
    "United States_Female_Standard_Smartphone",
    "Canada_Female_Standard_Tablet",
    "United States_Male_Basic_Smart TV",
    "United States_Male_Premium_Smartphone",
    "Canada_Male_Basic_Smart TV",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Premium_Smart TV",
    "Germany_Female_Basic_Smart TV",
    "France_Female_Premium_Tablet",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Female_Standard_Smartphone",
    "Italy_Male_Basic_Smartphone",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Smartphone",
    "Canada_Male_Premium_Tablet",
    "United States_Male_Basic_Smartphone",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Male_Standard_Tablet",
    "Australia_Female_Standard_Smartphone",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Smartphone",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Tablet",
    "Spain_Male_Premium_Smartphone",
    "Italy_Female_Basic_Tablet",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Basic_Smartphone",
    "United States_Male_Standard_Laptop",
    "Canada_Female_Standard_Tablet",
    "United States_Male_Basic_Smartphone",
    "United States_Male_Premium_Smart TV",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Female_Premium_Smartphone",
    "Germany_Male_Basic_Tablet",
    "France_Male_Premium_Smart TV",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Tablet",
    "Spain_Female_Standard_Smart TV",
    "Italy_Female_Basic_Laptop",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Basic_Smart TV",
    "United States_Male_Standard_Smart TV",
    "Canada_Male_Premium_Smart TV",
    "United States_Male_Basic_Smart TV",
    "United States_Male_Basic_Smart TV",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Laptop",
    "France_Male_Basic_Tablet",
    "Brazil_Female_Premium_Tablet",
    "Mexico_Female_Standard_Laptop",
    "Spain_Male_Standard_Smart TV",
    "Italy_Female_Basic_Smartphone",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Standard_Smart TV",
    "United States_Male_Basic_Tablet",
    "Canada_Female_Standard_Smartphone",
    "United States_Male_Premium_Laptop",
    "United States_Male_Basic_Smartphone",
    "Canada_Male_Premium_Smartphone",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Basic_Smartphone",
    "Germany_Male_Standard_Laptop",
    "France_Male_Premium_Tablet",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Female_Standard_Laptop",
    "Spain_Female_Premium_Tablet",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Smartphone",
    "Spain_Female_Basic_Smart TV",
    "United States_Female_Standard_Smart TV",
    "Canada_Female_Standard_Tablet",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Smartphone",
    "Canada_Female_Basic_Smart TV",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Female_Premium_Smart TV",
    "Germany_Male_Basic_Laptop",
    "France_Male_Premium_Smartphone",
    "Brazil_Male_Basic_Smartphone",
    "Mexico_Female_Standard_Smartphone",
    "Spain_Male_Standard_Laptop",
    "Italy_Male_Basic_Tablet",
    "Spain_Female_Premium_Smartphone",
    "Spain_Male_Basic_Smartphone",
    "United States_Female_Standard_Smart TV",
    "Canada_Female_Premium_Smart TV",
    "United States_Male_Basic_Smartphone",
    "United States_Male_Premium_Smart TV",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Male_Standard_Laptop",
    "Australia_Female_Standard_Smartphone",
    "Germany_Female_Basic_Laptop",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Male_Standard_Tablet",
    "Spain_Male_Premium_Tablet",
    "Italy_Male_Basic_Laptop",
    "Spain_Male_Premium_Smart TV",
    "Spain_Female_Basic_Tablet",
    "United States_Male_Standard_Smart TV",
    "Canada_Male_Standard_Smartphone",
    "United States_Female_Basic_Smartphone",
    "United States_Female_Premium_Laptop",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Premium_Smart TV",
    "Germany_Male_Basic_Tablet",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Smartphone",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Standard_Smart TV",
    "Italy_Female_Basic_Smartphone",
    "Spain_Female_Premium_Tablet",
    "Spain_Male_Basic_Tablet",
    "United States_Female_Standard_Tablet",
    "Canada_Female_Premium_Smartphone",
    "United States_Female_Basic_Smart TV",
    "United States_Male_Basic_Smartphone",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Male_Standard_Smart TV",
    "Australia_Male_Premium_Tablet",
    "Germany_Male_Basic_Laptop",
    "France_Female_Basic_Laptop",
    "Brazil_Female_Premium_Smartphone",
    "Mexico_Male_Standard_Laptop",
    "Spain_Female_Standard_Tablet",
    "Italy_Female_Basic_Smart TV",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Standard_Smartphone",
    "United States_Female_Basic_Smartphone",
    "Canada_Female_Standard_Laptop",
    "United States_Male_Premium_Smartphone",
    "United States_Female_Basic_Smartphone",
    "Canada_Female_Premium_Smart TV",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Male_Basic_Smart TV",
    "Germany_Male_Standard_Smart TV",
    "France_Male_Premium_Tablet",
    "Brazil_Male_Basic_Smart TV",
    "Mexico_Female_Standard_Laptop",
    "Spain_Male_Premium_Smart TV",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Basic_Smart TV",
    "United States_Male_Standard_Laptop",
    "Canada_Female_Standard_Laptop",
    "United States_Male_Basic_Tablet",
    "United States_Male_Premium_Smartphone",
    "Canada_Female_Basic_Smartphone",
    "United Kingdom_Female_Standard_Tablet",
    "Australia_Female_Premium_Smartphone",
    "Germany_Female_Basic_Tablet",
    "France_Female_Premium_Smart TV",
    "Brazil_Female_Basic_Tablet",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Standard_Smart TV",
    "Italy_Male_Basic_Smartphone",
    "Spain_Female_Premium_Smart TV",
    "Spain_Male_Basic_Smart TV",
    "United States_Female_Standard_Smart TV",
    "Canada_Female_Premium_Laptop",
    "United States_Female_Basic_Laptop",
    "United States_Female_Premium_Smartphone",
    "Canada_Male_Basic_Smartphone",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Female_Standard_Smartphone",
    "Germany_Female_Basic_Smartphone",
    "France_Male_Premium_Tablet",
    "Brazil_Male_Basic_Tablet",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Premium_Smart TV",
    "Italy_Female_Basic_Smartphone",
    "Spain_Female_Premium_Tablet",
    "Spain_Female_Basic_Tablet",
    "United States_Female_Standard_Smartphone",
    "Canada_Male_Standard_Smartphone",
    "United States_Female_Basic_Tablet",
    "United States_Male_Premium_Smartphone",
    "Canada_Male_Basic_Tablet",
    "United Kingdom_Female_Standard_Smart TV",
    "Australia_Male_Premium_Smart TV",
    "Germany_Female_Basic_Smart TV",
    "France_Male_Premium_Laptop",
    "Brazil_Female_Basic_Smart TV",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Female_Standard_Smartphone",
    "Italy_Male_Basic_Tablet",
    "Spain_Male_Premium_Laptop",
    "Spain_Female_Basic_Smartphone",
    "United States_Female_Standard_Smartphone",
    "Canada_Male_Premium_Laptop",
    "United States_Female_Basic_Tablet",
    "United States_Male_Basic_Smartphone",
    "Canada_Female_Basic_Tablet",
    "United Kingdom_Female_Standard_Laptop",
    "Australia_Male_Premium_Smart TV",
    "Germany_Female_Basic_Tablet",
    "France_Male_Basic_Tablet",
    "Brazil_Male_Premium_Laptop",
    "Mexico_Male_Standard_Tablet",
    "Spain_Female_Standard_Laptop",
    "Italy_Male_Basic_Laptop",
    "Spain_Female_Premium_Laptop",
    "Spain_Female_Standard_Laptop",
    "United States_Male_Basic_Laptop",
    "Canada_Female_Standard_Smart TV",
    "United States_Female_Premium_Tablet",
    "United States_Female_Basic_Smartphone",
    "Canada_Male_Premium_Smart TV",
    "United Kingdom_Female_Standard_Smartphone",
    "Australia_Female_Basic_Smartphone",
    "Germany_Male_Standard_Smart TV",
    "France_Female_Premium_Smartphone",
    "Brazil_Female_Basic_Laptop",
    "Mexico_Male_Standard_Smart TV",
    "Spain_Male_Premium_Smart TV",
    "Italy_Female_Basic_Laptop",
    "Spain_Female_Premium_Smart TV",
    "Spain_Female_Basic_Smart TV",
    "United States_Male_Standard_Laptop",
    "Canada_Female_Standard_Tablet",
    "United States_Female_Basic_Smart TV"
]